### ISSUE TITLE
Rare Low music level on CD music

### ISSUE THREAD

**Issue by Catarax** [kode54/foo_hdcd#1]
This is a bit a rare case, but I have one track on my library that played at a lower level than the album.
ReplayGain was set to none in the 2 options.

To get the original volume back of the track, I have to discover and remove foo_hdcd from my user components.

**The track :**
- Pleymo - Tank Club from Doctor Tank's Medicine Cake Album 
(the french release of the album didn't suffer of the bug).

This album is a CD pressing only, no HDCD material inside and it seems decoded for some unknow reason.

**Comment by kode54** [comment]
If you email me at chris@kode54 with further details, I will look into it.

**Comment by Catarax** [comment]
Email sent.

**Comment by kode54** [comment]
What you have discovered is a rarity: An HDCD processed/recorded track on an otherwise non-HDCD disc. Check the scanner, and I can upload a simple scanner you can verify with as well. It has HDCD signaling throughout the track, and it makes use of the Peak Extension feature, whereby the original samples have been squashed/compressed like for tape mastering, and the HDCD decoder extends peaks from ±0.70 to ±1.0 are extended on a logarithmic like scale to about ±2.0. This is combined with an optional 0.5x volume scale, which you may turn off.

You're welcome to negate the HDCD volume scaling by setting it to never reduce the volume in Advanced Preferences, but you'll want to rescan your tracks.

**Comment by Catarax** [comment]
Thanks for the details!
